### ISSUE TITLE
`where` parameter is not being used

### ISSUE THREAD

**Issue by jschwertfeger** [colepatrickturner/graphql-rails-resolver#1]
Hi there,

Great little gem, thanks for this!

I think the `where` param is broken in the current implementation. In the docs the example

`resolve :createdAt, :where => :created_at`

should result in the GraphQL argument `createdAt` being mapped to the model's `created_at` field. However, the particular line of code that would do this (https://github.com/colepatrickturner/graphql-rails-resolver/blob/master/lib/graphql/rails/resolver.rb#L89) is never reached because of the `params.size < 1` check a bit further up (https://github.com/colepatrickturner/graphql-rails-resolver/blob/master/lib/graphql/rails/resolver.rb#L77). Probably just a glitch due to some refactoring.

I didn't create a pull request though because I am not sure how that params size check was originally intended.

Cheers,
-Jonas

**Comment by colepatrickturner** [comment]
Ah yes - this bug was caused by a refactor and late night commits :)

The `params.size` was initially intended as a switch to the ArgumentError below it, for example if someone tried `resolve :argument1, :this_option_doesnt => :exist` it would skip over and raise an argument error.

Please give this commit a try - I've tested it against a small application as unit tests are still on the future agenda of this gem:

https://github.com/colepatrickturner/graphql-rails-resolver/commit/8e88ef5fad459df6906e25f64f8857b0e51a0d11

**Comment by jschwertfeger** [comment]
Works for me, thanks!
